services:
  - type: web
    name: n8n
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: true
      - key: N8N_BASIC_AUTH_USER
        value: 5054creator
      - key: N8N_BASIC_AUTH_PASSWORD
        value: n8n5054creator!Sosa
